### ISSUE TITLE
 indexedDB.webkitGetDatabaseNames is not a function 

### ISSUE THREAD

**Issue by yyvanovitch** [agershun/alasql#126]
I'm trying to use alasql with indexedDB, it works OK in chrome, 
but it does not work in Firefox 37.0.1 or IE

I've used example found on  http://jsfiddle.net/1t2rrr78/

With Firefox 37.0.1, I got this error
TypeError: indexedDB.webkitGetDatabaseNames is not a function

**Comment by agershun** [comment]
Yes, sorry, this is old bug. I will try to fix it today. 

Отправлено с iPhone

**Comment by agershun** [comment]
I fixed it, but... jsFiddle does not allow to access indexedDB variable in Firefox, and I do not know how to win over it. So you can test it  from the following url:

http://alasql.org/examples/indexeddb/

It works at least with my FF 37.0.1 OSX (and Chrome as well). 

Thank you for the bug! :+1:

**Comment by yyvanovitch** [comment]
It's OK now, i've tested with firefox 37.0.2 and Internet Explorer 11.0 on windows7
Great job, thanks a lot.

**Comment by agershun** [comment]
Thank you for tests!
